### ISSUE TITLE
ImportError??

### ISSUE THREAD

**Issue by H-Alireza** [AminAlam/Freelancing-Channel-Manager#1]
I got this error: 
ImportError: cannot import name 'chatAction' from 'telegram' (C:\Users\Asus\anaconda3\lib\site-packages\telegram\__init__.py)

any idea of what is going on?
guess it's for dependencies versions.
any requirement.txt file?

**Comment by H-Alireza** [comment]
installing version 13.5 of python-telegram-bot would fix it.
`pip install python-telegram-bot==13.5`
Also using these lines of code for importing dependencies may help: 
```
import logging
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters, CallbackQueryHandler
from telegram import Bot, ChatMember, InlineKeyboardMarkup, InlineKeyboardButton, ReplyKeyboardMarkup
from telegram.chataction import ChatAction
from telegram.parsemode import ParseMode
import os
import time
import datetime
from os.path import join as pjoin

```

**Comment by AminAlam** [comment]
Thanks for the comments and the code Alireza.
