### ISSUE TITLE
I don't know if this is a python dependency issue, please help. 

### ISSUE THREAD

**Issue by premnathdey** [AminAlam/Freelancing-Channel-Manager#2]
![Screenshot 2023-04-23 at 11 49 45 PM](https://user-images.githubusercontent.com/36821368/233857998-322b5c88-2b57-4cde-a769-7812ba347635.png)
The python version I am using is python3.11.

**Comment by AminAlam** [comment]
The BIT_API variable should be a simple string. I think you have assigned a tuple to it.

**Comment by premnathdey** [comment]
You mean BOT_API generated from BOT_father. That was incorrect previously but I corrected it still getting the same error.

**Comment by AminAlam** [comment]
Please put the following line of code just before `updater = Updater(...)` and send the results here.
`print(type(BOT_API))`

**Comment by premnathdey** [comment]
<class 'tuple'>

**Comment by AminAlam** [comment]
BOT_API should be a string, but it seems that you have assigned a tuple to it. It should be similar to this:
`BOT_API = '1466026381:AAF-N7tHZYin4heYfr6yLoMPCyM9RvUscoc'`

**Comment by premnathdey** [comment]
I can please share me your telegram id, I am still not able to solve the issue.

**Comment by AminAlam** [comment]
t.me/Alam_Amin

**Comment by AminAlam** [comment]
There were two extra commas in the configs.py causing the error.
