### ISSUE TITLE
telegram.error.BadRequest: Chat not found

### ISSUE THREAD

**Issue by erkanyldz34** [AminAlam/Freelancing-Channel-Manager#3]
![Ekran görüntüsü 2024-03-01 183455](https://github.com/AminAlam/Freelancing-Channel-Manager/assets/117810531/c7a74b3f-0cd3-4375-88db-8a034c07a4e6)
When the owner id here is 1, this error happens and it says do not change it. But somewhere in the code, I get a chat not found error when the owner id is not equal to the admin id.

**Comment by AminAlam** [comment]
Hi, You need to set the ADMIN_PASSWORD field in configs.py, and send it to the bot via the admin user.
